POST {{path}}/location
Content-Type: application/json

{
  "addressList": [
    {
      "id": 1,
      "address" : "Cra. 104 #148 - 07, Bogotá, Cundinamarca"
    },
    {
      "id": 2,
      "address": "Cl. 142 #111A-06, Suba, Bogotá"
    }
  ],
  "input": "Cra 17a # 175-82"
}
###

POST {{path}}/location
Content-Type: application/json

{
  "input": "Cra 17a # 175-82"
}
